spring:
  config:
    activate:
      on-profile: rds
  session:
    store-type: jdbc
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver